apiVersion: v1
kind: ConfigMap
metadata:
  name: demoservice-config
  namespace: dev
  annotations:
    'moniker.spinnaker.io/stack': 'dev'
    'strategy.spinnaker.io/versioned': 'false'
  labels:
    app: demoservice
    env: dev
data:
    args: --fullTables --alpha-factors --start=2018-09-12 --demo-env=devTest
#  fullTables:
#  alpha-factors:
#  start: 2018-09-12
#  demo-env: devTest

#$data:
# special.how: very
#  special.type: charm
--
# In deployment
  env:
    - name: SPINNAKER_ARGS
      valueFrom:
        configMapKeyRef:
          name: demoservice-config
          key: args
          optional: false

# Not 100% sure this will work.
  args:
    - "$(SPINNAKER_ARGS)"



    - "$(CLA_ALPHA_FACTORS)"
    - "$(CLA_DEMO_ENV)"
#
#      env:
#        - name: SPECIAL_LEVEL_KEY
#          valueFrom:
#            configMapKeyRef:
#              name: special-config
#              key: special.how
#        - name: SPECIAL_TYPE_KEY
#          valueFrom:
#            configMapKeyRef:
#              name: special-config
#              key: special.type